---
name: Build

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ./test.sh
  # Push image to DockerHub
  upload:
    needs: build
    runs-on: ubuntu-latest
    env:
      name: openmicroscopy/vsftpd-anonymous-upload
    steps:
      - name: Get prefix
        id: getprefix
        run: |
          if [ ! -z ${{ env.name }} ]; then
            echo "prefix=${{ env.name }}:" >> $GITHUB_OUTPUT
          else
            echo "prefix=${{ github.repository }}:" >> $GITHUB_OUTPUT
          fi
      - name: Get other tags
        id: gettags
        uses: jupyterhub/action-major-minor-tag-calculator@v1.1.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          prefix: "${{ steps.getprefix.outputs.prefix }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: startsWith(github.ref, 'refs/tags')
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: ${{ join(fromJson(steps.gettags.outputs.tags)) }}
          push: ${{ startsWith(github.ref, 'refs/tags') }}
